/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './random';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/loading/loading';
import * as import11 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import12 from '../../providers/reddit-service';
import * as import13 from 'ionic-angular/components/alert/alert';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/refresher/refresher.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import30 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll.ngfactory';
import * as import32 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll-content.ngfactory';
import * as import33 from 'ionic-angular/config/config';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from 'ionic-angular/navigation/view-controller';
import * as import36 from 'ionic-angular/components/app/app';
import * as import37 from 'ionic-angular/components/toolbar/toolbar';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from '@angular/core/src/linker/template_ref';
import * as import43 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import44 from '@angular/forms/src/directives/ng_model';
import * as import45 from '@angular/forms/src/directives/ng_control';
import * as import46 from '@angular/forms/src/directives/ng_control_status';
import * as import47 from 'ionic-angular/components/searchbar/searchbar';
import * as import48 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import49 from 'ionic-angular/components/icon/icon';
import * as import50 from 'ionic-angular/components/button/button';
import * as import51 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import52 from 'ionic-angular/components/navbar/navbar';
import * as import53 from 'ionic-angular/components/refresher/refresher-content';
import * as import54 from 'ionic-angular/components/refresher/refresher';
import * as import55 from '@angular/common/src/directives/ng_for';
import * as import56 from 'ionic-angular/components/list/list';
import * as import57 from 'ionic-angular/components/infinite-scroll/infinite-scroll-content';
import * as import58 from 'ionic-angular/components/infinite-scroll/infinite-scroll';
import * as import59 from 'ionic-angular/components/content/content';
import * as import60 from '@angular/core/src/security';
import * as import61 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import62 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import63 from 'ionic-angular/util/form';
import * as import64 from 'ionic-angular/components/item/item-reorder';
import * as import65 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import66 from 'ionic-angular/components/item/item';
export class Wrapper_RandomPage {
  context:import0.RandomPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this.changed = false;
    this.context = new import0.RandomPage(p0,p1,p2,p3,p4,p5);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RandomPage_Host:import2.RenderComponentType = (null as any);
class _View_RandomPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RandomPage_0_4:Wrapper_RandomPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RandomPage_Host0,renderType_RandomPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-random',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RandomPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RandomPage_0_4 = new Wrapper_RandomPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Http),this.parentInjector.get(import10.LoadingController),this.parentInjector.get(import11.ActionSheetController),this.parentInjector.get(import12.RedditService),this.parentInjector.get(import13.AlertController));
    this._appEl_0.initComponent(this._RandomPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RandomPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RandomPage) && (0 === requestNodeIndex))) { return this._RandomPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RandomPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RandomPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RandomPage_Host === (null as any))) { (renderType_RandomPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RandomPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RandomPageNgFactory:import15.ComponentFactory<import0.RandomPage> = new import15.ComponentFactory<import0.RandomPage>('page-random',viewFactory_RandomPage_Host0,import0.RandomPage);
const styles_RandomPage:any[] = ([] as any[]);
var renderType_RandomPage:import2.RenderComponentType = (null as any);
class _View_RandomPage0 extends import1.AppView<import0.RandomPage> {
  _viewQuery_Content_0:import16.QueryList<any>;
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import19.Wrapper_ToolbarTitle;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _NgModel_6_4:import20.Wrapper_NgModel;
  _NgControl_6_5:any;
  _NgControlStatus_6_6:import21.Wrapper_NgControlStatus;
  _Searchbar_6_7:import22.Wrapper_Searchbar;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ToolbarItem_10_3:import23.Wrapper_ToolbarItem;
  _query_Button_10_0:import16.QueryList<any>;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _Button_12_4:import24.Wrapper_Button;
  _text_13:any;
  _el_14:any;
  _Icon_14_3:import25.Wrapper_Icon;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Content_20_4:import26.Wrapper_Content;
  _text_21:any;
  _el_22:any;
  _Refresher_22_3:import27.Wrapper_Refresher;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _RefresherContent_24_4:import28.Wrapper_RefresherContent;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _List_29_3:import29.Wrapper_List;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _TemplateRef_31_5:any;
  _NgFor_31_6:import30.Wrapper_NgFor;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _InfiniteScroll_34_3:import31.Wrapper_InfiniteScroll;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _InfiniteScrollContent_36_4:import32.Wrapper_InfiniteScrollContent;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RandomPage0,renderType_RandomPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Content_0 = new import16.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import35.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import36.App),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n		 Meu Feed\n		 ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-searchbar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'color','primary');
    this.renderer.setElementAttribute(this._el_6,'placeholder','Pesquise aqui...');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import22.viewFactory_Searchbar0(this.viewUtils,this.injector(6),this._appEl_6);
    this._NgModel_6_4 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_6_5 = this._NgModel_6_4.context;
    this._NgControlStatus_6_6 = new import21.Wrapper_NgControlStatus(this._NgControl_6_5);
    this._Searchbar_6_7 = new import22.Wrapper_Searchbar(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer,this._NgControl_6_5);
    this._appEl_6.initComponent(this._Searchbar_6_7.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n		',(null as any));
    compView_6.create(this._Searchbar_6_7.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n	 ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_10,'end','');
    this._ToolbarItem_10_3 = new import23.Wrapper_ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_10_0 = new import16.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n\n		 ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'icon-only','');
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this.renderer.setElementAttribute(this._el_12,'style','top:6px;');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import24.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n			 ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'name','sync');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this._Icon_14_3 = new import25.Wrapper_Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'\n		 ',(null as any));
      compView_12.create(this._Button_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_15
      ]
    )],(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n\n	 ',(null as any));
    this._text_17 = this.renderer.createText((null as any),' \n \n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_10]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_9,
        this._text_17
      ]
      )
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_20,'padding','');
    this._appEl_20 = new import3.AppElement(20,(null as any),this,this._el_20);
    var compView_20:any = import26.viewFactory_Content0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Content_20_4 = new import26.Wrapper_Content(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import36.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_20.initComponent(this._Content_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_22_3 = new import27.Wrapper_Refresher(this._Content_20_4.context,this.parentInjector.get(import39.NgZone),this.parentInjector.get(import41.GestureController));
    this._text_23 = this.renderer.createText(this._el_22,'\n		',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_24,'pullMax','200');
    this.renderer.setElementAttribute(this._el_24,'pullMin','100');
    this.renderer.setElementAttribute(this._el_24,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_24,'pullingText','Puxe para atualizar');
    this.renderer.setElementAttribute(this._el_24,'refreshingSpinner','circles');
    this.renderer.setElementAttribute(this._el_24,'refreshingText','Atualizando...');
    this.renderer.setElementAttribute(this._el_24,'snapbackDuration','100');
    this._appEl_24 = new import3.AppElement(24,22,this,this._el_24);
    var compView_24:any = import28.viewFactory_RefresherContent0(this.viewUtils,this.injector(24),this._appEl_24);
    this._RefresherContent_24_4 = new import28.Wrapper_RefresherContent(this._Refresher_22_3.context,this.parentInjector.get(import33.Config));
    this._appEl_24.initComponent(this._RefresherContent_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'			\n		',(null as any));
    compView_24.create(this._RefresherContent_24_4.context,([] as any[]),(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'		\n	',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n\n		',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_29_3 = new import29.Wrapper_List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_29),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_30 = this.renderer.createText(this._el_29,'\n			',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_29,(null as any));
    this._appEl_31 = new import3.AppElement(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import42.TemplateRef_(this._appEl_31,viewFactory_RandomPage1);
    this._NgFor_31_6 = new import30.Wrapper_NgFor(this._appEl_31.vcRef,this._TemplateRef_31_5,this.parentInjector.get(import43.IterableDiffers),this.ref);
    this._text_32 = this.renderer.createText(this._el_29,'\n		',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n	\n	',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-infinite-scroll',(null as any));
    this._InfiniteScroll_34_3 = new import31.Wrapper_InfiniteScroll(this._Content_20_4.context,this.parentInjector.get(import39.NgZone),new import34.ElementRef(this._el_34));
    this._text_35 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-infinite-scroll-content',(null as any));
    this.renderer.setElementAttribute(this._el_36,'loadingText','Carregando Noticias...');
    this._appEl_36 = new import3.AppElement(36,34,this,this._el_36);
    var compView_36:any = import32.viewFactory_InfiniteScrollContent0(this.viewUtils,this.injector(36),this._appEl_36);
    this._InfiniteScrollContent_36_4 = new import32.Wrapper_InfiniteScrollContent(this._InfiniteScroll_34_3.context,this.parentInjector.get(import33.Config));
    this._appEl_36.initComponent(this._InfiniteScrollContent_36_4.context,([] as any[]),compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_36.create(this._InfiniteScrollContent_36_4.context,([] as any[]),(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n   ',(null as any));
    this._text_39 = this.renderer.createText((null as any),' \n',(null as any));
    compView_20.create(this._Content_20_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_21,
        this._text_27,
        this._text_28,
        this._el_29,
        this._text_33,
        this._el_34,
        this._text_39
      ]
      ),
      ([] as any[]).concat([this._el_22])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'ngModelChange',this.eventHandler(this._handle_ngModelChange_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_6,'ionInput',this.eventHandler(this._handle_ionInput_6_1.bind(this)));
    const subscription_0:any = this._NgModel_6_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_6_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    const subscription_1:any = this._Searchbar_6_7.context.ionInput.subscribe(this.eventHandler(this._handle_ionInput_6_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_22,'ionRefresh',this.eventHandler(this._handle_ionRefresh_22_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    const subscription_2:any = this._Refresher_22_3.context.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_22_0.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_34,'ionInfinite',this.eventHandler(this._handle_ionInfinite_34_0.bind(this)));
    const subscription_3:any = this._InfiniteScroll_34_3.context.ionInfinite.subscribe(this.eventHandler(this._handle_ionInfinite_34_0.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    this._viewQuery_Content_0.reset([this._Content_20_4.context]);
    this.context.content = this._viewQuery_Content_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.NgModel) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgModel_6_4.context; }
    if (((token === import45.NgControl) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgControl_6_5; }
    if (((token === import46.NgControlStatus) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgControlStatus_6_6.context; }
    if (((token === import47.Searchbar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Searchbar_6_7.context; }
    if (((token === import48.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import49.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3.context; }
    if (((token === import50.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Button_12_4.context; }
    if (((token === import51.ToolbarItem) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ToolbarItem_10_3.context; }
    if (((token === import52.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Navbar_2_4.context; }
    if (((token === import37.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Header_0_3.context; }
    if (((token === import53.RefresherContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RefresherContent_24_4.context; }
    if (((token === import54.Refresher) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Refresher_22_3.context; }
    if (((token === import42.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import55.NgFor) && (31 === requestNodeIndex))) { return this._NgFor_31_6.context; }
    if (((token === import56.List) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._List_29_3.context; }
    if (((token === import57.InfiniteScrollContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._InfiniteScrollContent_36_4.context; }
    if (((token === import58.InfiniteScroll) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._InfiniteScroll_34_3.context; }
    if (((token === import59.Content) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Content_20_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'secondary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_5:any = this.context.searchTerm;
    this._NgModel_6_4.check_model(currVal_5,throwOnChange,false);
    this._NgModel_6_4.detectChangesInternal(this,this._el_6,throwOnChange);
    this._NgControlStatus_6_6.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_12:any = 'primary';
    this._Searchbar_6_7.check_color(currVal_12,throwOnChange,false);
    const currVal_13:any = 'Pesquise aqui...';
    this._Searchbar_6_7.check_placeholder(currVal_13,throwOnChange,false);
    this._Searchbar_6_7.detectChangesInternal(this,this._el_6,throwOnChange);
    this._ToolbarItem_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    if (this._Button_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    const currVal_21:any = 'sync';
    this._Icon_14_3.check_name(currVal_21,throwOnChange,false);
    this._Icon_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    if (this._Content_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._Refresher_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_27:any = 'arrow-dropdown';
    this._RefresherContent_24_4.check_pullingIcon(currVal_27,throwOnChange,false);
    const currVal_28:any = 'Puxe para atualizar';
    this._RefresherContent_24_4.check_pullingText(currVal_28,throwOnChange,false);
    const currVal_29:any = 'circles';
    this._RefresherContent_24_4.check_refreshingSpinner(currVal_29,throwOnChange,false);
    const currVal_30:any = 'Atualizando...';
    this._RefresherContent_24_4.check_refreshingText(currVal_30,throwOnChange,false);
    this._RefresherContent_24_4.detectChangesInternal(this,this._el_24,throwOnChange);
    this._List_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_32:any = this.context.noticias;
    this._NgFor_31_6.check_ngForOf(currVal_32,throwOnChange,false);
    this._NgFor_31_6.detectChangesInternal(this,this._anchor_31,throwOnChange);
    this._InfiniteScroll_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    const currVal_34:any = 'Carregando Noticias...';
    this._InfiniteScrollContent_36_4.check_loadingText(currVal_34,throwOnChange,false);
    this._InfiniteScrollContent_36_4.detectChangesInternal(this,this._el_36,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_10_0.dirty) {
        this._query_Button_10_0.reset([this._Button_12_4.context]);
        this._ToolbarItem_10_3.context._buttons = this._query_Button_10_0;
        this._query_Button_10_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Searchbar_6_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._InfiniteScroll_34_3.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._NgControlStatus_6_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_6_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_6_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_6_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_6_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_6_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = this._Searchbar_6_7.context.animated;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_6,'searchbar-animated',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._Searchbar_6_7.context._value;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_6,'searchbar-has-value',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._Searchbar_6_7.context._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_6,'searchbar-active',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._Searchbar_6_7.context.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_6,'searchbar-show-cancel',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Searchbar_6_7.context._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_6,'searchbar-left-aligned',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._Searchbar_6_7.context._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_6,'searchbar-has-focus',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = this._Icon_14_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._Content_20_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_20,'statusbar-padding',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = (this._Refresher_22_3.context.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_22,'refresher-active',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._Refresher_22_3.context._top;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementStyle(this._el_22,'top',((this.viewUtils.sanitizer.sanitize(import60.SecurityContext.STYLE,currVal_26) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import60.SecurityContext.STYLE,currVal_26).toString()));
      this._expr_26 = currVal_26;
    }
    const currVal_31:any = this._RefresherContent_24_4.context.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementAttribute(this._el_24,'state',((currVal_31 == (null as any))? (null as any): currVal_31.toString()));
      this._expr_31 = currVal_31;
    }
    const currVal_35:any = this._InfiniteScrollContent_36_4.context.inf.state;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementAttribute(this._el_36,'state',((currVal_35 == (null as any))? (null as any): currVal_35.toString()));
      this._expr_35 = currVal_35;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_6_4.context.ngOnDestroy();
    this._Icon_14_3.context.ngOnDestroy();
    this._Refresher_22_3.context.ngOnDestroy();
    this._InfiniteScroll_34_3.context.ngOnDestroy();
    this._Content_20_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.searchTerm = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.filterItems()) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resetaLista()) !== false);
    return (true && pd_0);
  }
  private _handle_ionRefresh_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInfinite_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doInfinite($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RandomPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RandomPage> {
  if ((renderType_RandomPage === (null as any))) { (renderType_RandomPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_RandomPage,{})); }
  return new _View_RandomPage0(viewUtils,parentInjector,declarationEl);
}
class _View_RandomPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import61.Wrapper_Item;
  _ItemContent_0_5:import61.Wrapper_ItemContent;
  _query_Label_0_0:import16.QueryList<any>;
  _query_Button_0_1:import16.QueryList<any>;
  _query_Icon_0_2:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Thumbnail_2_3:import62.Wrapper_Thumbnail;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RandomPage1,renderType_RandomPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import61.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import61.Wrapper_Item(this.parent.parentInjector.get(import63.Form),this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import64.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import61.Wrapper_ItemContent();
    this._query_Label_0_0 = new import16.QueryList<any>();
    this._query_Button_0_1 = new import16.QueryList<any>();
    this._query_Icon_0_2 = new import16.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),' \n				',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-right','');
    this._Thumbnail_2_3 = new import62.Wrapper_Thumbnail();
    this._text_3 = this.renderer.createText(this._el_2,'\n					',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'h2',(null as any));
    this.renderer.setElementAttribute(this._el_7,'style','text-align:justify');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'			\n				',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_10,'style','color:blue');
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_13,'style','color:black');
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText((null as any),'	\n			',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_9,
        this._el_10,
        this._text_12,
        this._el_13,
        this._text_15
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_2])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import65.Thumbnail) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Thumbnail_2_3.context; }
    if (((token === import66.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_0_4.context; }
    if (((token === import66.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Thumbnail_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this.context.$implicit.data.thumbnail;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import60.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.data.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.data.author,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_11,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'Ups: ',this.context.$implicit.data.ups,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_14,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemSelecionado(this.context.$implicit.data.url)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_RandomPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RandomPage1(viewUtils,parentInjector,declarationEl);
}