/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './tabs';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/tabs/tabs.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/tabs/tab.ngfactory';
import * as import13 from 'ionic-angular/navigation/view-controller';
import * as import14 from 'ionic-angular/components/app/app';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/platform/platform';
import * as import18 from 'ionic-angular/navigation/deep-linker';
import * as import19 from 'ionic-angular/util/keyboard';
import * as import20 from '@angular/core/src/zone/ng_zone';
import * as import21 from '@angular/core/src/linker/component_factory_resolver';
import * as import22 from 'ionic-angular/gestures/gesture-controller';
import * as import23 from 'ionic-angular/transitions/transition-controller';
import * as import24 from 'ionic-angular/components/tabs/tab';
import * as import25 from 'ionic-angular/components/tabs/tabs';
export class Wrapper_TabsPage {
  context:import0.TabsPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.TabsPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_TabsPage_Host:import2.RenderComponentType = (null as any);
class _View_TabsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TabsPage_0_4:Wrapper_TabsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TabsPage_Host0,renderType_TabsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TabsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TabsPage_0_4 = new Wrapper_TabsPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._TabsPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TabsPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TabsPage) && (0 === requestNodeIndex))) { return this._TabsPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TabsPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TabsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TabsPage_Host === (null as any))) { (renderType_TabsPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TabsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TabsPageNgFactory:import10.ComponentFactory<import0.TabsPage> = new import10.ComponentFactory<import0.TabsPage>('ng-component',viewFactory_TabsPage_Host0,import0.TabsPage);
const styles_TabsPage:any[] = ([] as any[]);
var renderType_TabsPage:import2.RenderComponentType = (null as any);
class _View_TabsPage0 extends import1.AppView<import0.TabsPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Tabs_1_4:import11.Wrapper_Tabs;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Tab_3_4:import12.Wrapper_Tab;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Tab_5_4:import12.Wrapper_Tab;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Tab_7_4:import12.Wrapper_Tab;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TabsPage0,renderType_TabsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-tabs',(null as any));
    this.renderer.setElementAttribute(this._el_1,'color','secondary');
    this.renderer.setElementAttribute(this._el_1,'tabsHighlight','true');
    this.renderer.setElementAttribute(this._el_1,'tabsPlacement','top');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import11.viewFactory_Tabs0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Tabs_1_4 = new import11.Wrapper_Tabs(this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import13.ViewController,(null as any)),this.parentInjector.get(import14.App),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_1),this.parentInjector.get(import17.Platform),this.renderer,this.parentInjector.get(import18.DeepLinker));
    this._appEl_1.initComponent(this._Tabs_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_3,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_3,'tabIcon','flame');
    this.renderer.setElementAttribute(this._el_3,'tabTitle','Hot');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Tab0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Tab_3_4 = new import12.Wrapper_Tab(this._Tabs_1_4.context,this.parentInjector.get(import14.App),this.parentInjector.get(import15.Config),this.parentInjector.get(import19.Keyboard),new import16.ElementRef(this._el_3),this.parentInjector.get(import20.NgZone),this.renderer,this.parentInjector.get(import21.ComponentFactoryResolver),compView_3.ref,this.parentInjector.get(import22.GestureController),this.parentInjector.get(import23.TransitionController),this.parentInjector.get(import18.DeepLinker,(null as any)));
    this._appEl_3.initComponent(this._Tab_3_4.context,([] as any[]),compView_3);
    compView_3.create(this._Tab_3_4.context,([] as any[]),(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_5,'dark','');
    this.renderer.setElementAttribute(this._el_5,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_5,'tabIcon','star');
    this.renderer.setElementAttribute(this._el_5,'tabTitle','New');
    this._appEl_5 = new import3.AppElement(5,1,this,this._el_5);
    var compView_5:any = import12.viewFactory_Tab0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Tab_5_4 = new import12.Wrapper_Tab(this._Tabs_1_4.context,this.parentInjector.get(import14.App),this.parentInjector.get(import15.Config),this.parentInjector.get(import19.Keyboard),new import16.ElementRef(this._el_5),this.parentInjector.get(import20.NgZone),this.renderer,this.parentInjector.get(import21.ComponentFactoryResolver),compView_5.ref,this.parentInjector.get(import22.GestureController),this.parentInjector.get(import23.TransitionController),this.parentInjector.get(import18.DeepLinker,(null as any)));
    this._appEl_5.initComponent(this._Tab_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._Tab_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-tab',(null as any));
    this.renderer.setElementAttribute(this._el_7,'role','tabpanel');
    this.renderer.setElementAttribute(this._el_7,'tabIcon','ribbon');
    this.renderer.setElementAttribute(this._el_7,'tabTitle','Top');
    this._appEl_7 = new import3.AppElement(7,1,this,this._el_7);
    var compView_7:any = import12.viewFactory_Tab0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Tab_7_4 = new import12.Wrapper_Tab(this._Tabs_1_4.context,this.parentInjector.get(import14.App),this.parentInjector.get(import15.Config),this.parentInjector.get(import19.Keyboard),new import16.ElementRef(this._el_7),this.parentInjector.get(import20.NgZone),this.renderer,this.parentInjector.get(import21.ComponentFactoryResolver),compView_7.ref,this.parentInjector.get(import22.GestureController),this.parentInjector.get(import23.TransitionController),this.parentInjector.get(import18.DeepLinker,(null as any)));
    this._appEl_7.initComponent(this._Tab_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._Tab_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText((null as any),'  \n',(null as any));
      compView_1.create(this._Tabs_1_4.context,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_4,
        this._el_5,
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Tab) && (3 === requestNodeIndex))) { return this._Tab_3_4.context; }
    if (((token === import24.Tab) && (5 === requestNodeIndex))) { return this._Tab_5_4.context; }
    if (((token === import24.Tab) && (7 === requestNodeIndex))) { return this._Tab_7_4.context; }
    if (((token === import25.Tabs) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Tabs_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'secondary';
    this._Tabs_1_4.check_color(currVal_0,throwOnChange,false);
    const currVal_1:any = 'top';
    this._Tabs_1_4.check_tabsPlacement(currVal_1,throwOnChange,false);
    const currVal_2:any = 'true';
    this._Tabs_1_4.check_tabsHighlight(currVal_2,throwOnChange,false);
    this._Tabs_1_4.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_3:any = this.context.randomPage;
    this._Tab_3_4.check_root(currVal_3,throwOnChange,false);
    const currVal_4:any = 'Hot';
    this._Tab_3_4.check_tabTitle(currVal_4,throwOnChange,false);
    const currVal_5:any = 'flame';
    this._Tab_3_4.check_tabIcon(currVal_5,throwOnChange,false);
    this._Tab_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    const currVal_8:any = this.context.homePage;
    this._Tab_5_4.check_root(currVal_8,throwOnChange,false);
    const currVal_9:any = 'New';
    this._Tab_5_4.check_tabTitle(currVal_9,throwOnChange,false);
    const currVal_10:any = 'star';
    this._Tab_5_4.check_tabIcon(currVal_10,throwOnChange,false);
    this._Tab_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_13:any = this.context.topPage;
    this._Tab_7_4.check_root(currVal_13,throwOnChange,false);
    const currVal_14:any = 'Top';
    this._Tab_7_4.check_tabTitle(currVal_14,throwOnChange,false);
    const currVal_15:any = 'ribbon';
    this._Tab_7_4.check_tabIcon(currVal_15,throwOnChange,false);
    this._Tab_7_4.detectChangesInternal(this,this._el_7,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_6:any = this._Tab_3_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementAttribute(this._el_3,'id',((currVal_6 == (null as any))? (null as any): currVal_6.toString()));
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Tab_3_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_3,'aria-labelledby',((currVal_7 == (null as any))? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
    const currVal_11:any = this._Tab_5_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementAttribute(this._el_5,'id',((currVal_11 == (null as any))? (null as any): currVal_11.toString()));
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Tab_5_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_5,'aria-labelledby',((currVal_12 == (null as any))? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = this._Tab_7_4.context._tabId;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_7,'id',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._Tab_7_4.context._btnId;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementAttribute(this._el_7,'aria-labelledby',((currVal_17 == (null as any))? (null as any): currVal_17.toString()));
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Tabs_1_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Tabs_1_4.context.ngOnDestroy();
  }
}
export function viewFactory_TabsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TabsPage> {
  if ((renderType_TabsPage === (null as any))) { (renderType_TabsPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_TabsPage,{})); }
  return new _View_TabsPage0(viewUtils,parentInjector,declarationEl);
}